development:
    adapter: postgresql
    database: total
    host: localhost
    username: postgres
    password: postgres

test:
    adapter: postgresql
    database: total
    host: localhost
    username: postgres
    password: postgres