development:
    adapter: postgresql
    database: total
    host: localhost
    username: postgres
    password: '12345'

test:
    adapter: postgresql
    database: total
    host: localhost
    username: postgres
    password: '12345'
    
